In [2]:
import numpy as np
mat1 = np.array([1,2,3,4,5])
print(mat1)
mat2 = np.array([[1,2,3],[4,5,6]])
print(mat2)
print(mat1.shape,mat2.shape)
print(np.zeros([4,5]),np.ones([3,6]))
mat2[1,2] = 10
print(mat2)
mat3 = np.ones([2,3])
print(mat3*2,mat3/2,mat3+1,mat3-2,mat3+mat2,mat3*mat2)
#在这个模块中 矩阵相乘是对应元素相乘 而非常见的矩阵乘法

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
(5,) (2, 3)
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] [[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[ 1  2  3]
 [ 4  5 10]]
[[2. 2. 2.]
 [2. 2. 2.]] [[0.5 0.5 0.5]
 [0.5 0.5 0.5]] [[2. 2. 2.]
 [2. 2. 2.]] [[-1. -1. -1.]
 [-1. -1. -1.]] [[ 2.  3.  4.]
 [ 5.  6. 11.]] [[ 1.  2.  3.]
 [ 4.  5. 10.]]
