In [1]:
import tensorflow as tf
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)
c = tf.add(a,b)
with tf.Session() as sess:
    print(sess.run(c,feed_dict={a:6,b:2}))

8.0


In [2]:
import tensorflow as tf
data1 = tf.constant([[6,1], 
                     [7,3],
                     [8,9]])
print(data1.shape)
with tf.Session() as sess:
    print(sess.run(data1))
    print(sess.run(data1[0,:]))
    print(sess.run(data1[:,0]))
    print(sess.run(data1[2,1]))

(3, 2)
[[6 1]
 [7 3]
 [8 9]]
[6 1]
[6 7 8]
9


In [20]:
mat0 = tf.constant([[1,2,3],[4,5,6]])
mat1 = tf.fill([2,3],2)
mat2 = tf.fill([3,2],1)
mat3 = tf.fill([2,3],0)
matAdd0 = tf.add(mat0,mat1)
matAdd1 = tf.add(mat1,mat0)
matMul0 = tf.matmul(mat0,mat2)
matMul1 = tf.matmul(mat1,mat2)
matMul2 = tf.matmul(mat2,mat0)
matMul3 = tf.matmul(mat3,mat2)
with tf.Session() as sess:
    print(sess.run([matAdd0,matAdd1,matMul0,matMul1,matMul2,matMul3]))
mat4 = tf.ones([2,3])
mat5 = tf.zeros([2,3])
matAdd2 = tf.add(mat4,mat5)
with tf.Session() as sess:
    print(sess.run(matAdd2))

[array([[3, 4, 5],
       [6, 7, 8]]), array([[3, 4, 5],
       [6, 7, 8]]), array([[ 6,  6],
       [15, 15]]), array([[6, 6],
       [6, 6]]), array([[5, 7, 9],
       [5, 7, 9],
       [5, 7, 9]]), array([[0, 0],
       [0, 0]])]
[[1. 1. 1.]
 [1. 1. 1.]]
